### GET ALL THE TASKS
GET http://localhost:5050/tasks

### GET AN SPECIFIC TASK
GET http://localhost:5050/tasks/1

### CREATE A NEW TASK
POST http://localhost:5050/tasks
Content-Type: application/json

{
    "title": "My new task",
    "description": "My new task description",
    "done": false,
    "author": "1"
}


